global:
  environment: staging
  imageTag: "latest"

api-gateway:
  replicaCount: 1
  resources:
    requests: { cpu: "50m", memory: "64Mi" }
    limits: { cpu: "200m", memory: "256Mi" }
  hpa:
    minReplicas: 1
    maxReplicas: 3

user-service:
  replicaCount: 1
  hpa:
    minReplicas: 1
    maxReplicas: 3

metrics-collector:
  replicaCount: 1
  hpa:
    minReplicas: 1
    maxReplicas: 2
