replicaCount: 2
image:
  name: autoops/user-service
service:
  type: ClusterIP
  port: 8000
resources: {}
logLevel: INFO
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
pdb:
  enabled: false
  minAvailable: 1
serviceAccount:
  create: true
  name: ""
